# -*- coding: utf-8 -*-
"""Prediccion PL 26/27.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1E0VIxWhG79z8DEMa24ZCq0oFeFGANq4V
"""

import pandas as pd

# ==========================================
# BLOQUE 1: EXTRACCIÓN Y LIMPIEZA
# ==========================================
file_path = "/content/Premier League.xlsx"
xls = pd.ExcelFile(file_path)
sheets = xls.sheet_names
all_seasons = []

for i, sheet in enumerate(sheets):
    weight = 10 - i
    df = pd.read_excel(file_path, sheet_name=sheet)

    if 'Squad' not in df.columns:
        col_name = df.columns[0]
        df_clean = df[col_name].astype(str).str.split(',', expand=True)
        df_clean.columns = [c.strip() for c in col_name.split(',')]
    else:
        df_clean = df.copy()
        df_clean.columns = [str(c).strip() for c in df_clean.columns]

    df_clean = df_clean[['Squad', 'Pts', 'GF', 'GA']].copy()
    for col in ['Pts', 'GF', 'GA']:
        df_clean[col] = pd.to_numeric(df_clean[col], errors='coerce')

    df_clean['Weight'] = weight
    all_seasons.append(df_clean)

df_all = pd.concat(all_seasons, ignore_index=True)

# ==========================================
# BLOQUE 2: MODELO MATEMÁTICO (PROMEDIO PONDERADO)
# ==========================================
def promedio_ponderado(grupo, columna):
    return (grupo[columna] * grupo['Weight']).sum() / grupo['Weight'].sum()

prediccion = df_all.groupby('Squad').apply(
    lambda x: pd.Series({
        'Expected_Pts': round(promedio_ponderado(x, 'Pts')),
        'Expected_GF': round(promedio_ponderado(x, 'GF')),
        'Expected_GA': round(promedio_ponderado(x, 'GA'))
    })
).reset_index()

# ==========================================
# BLOQUE 3: FILTRO DE LA TEMPORADA 2026-2027
# ==========================================
equipos_usuario = [
    "Bournemouth", "Arsenal", "Aston Villa", "Brentford", "Brighton",
    "Chelsea", "Coventry City", "Crystal Palace", "Everton", "Fulham",
    "Hull City", "Ipswich", "Leeds", "Liverpool", "Manchester City",
    "Manchester United", "Newcastle", "Nottingham Forest", "Sunderland AFC", "Tottenham"
]

# Diccionario para que Python entienda los nombres de la base de datos
traductor_bd = {
    "Manchester United": "Manchester Utd",
    "Nottingham Forest": "Nottingham", "Sunderland AFC": "Sunderland",
    "Leeds": "Leeds United", "Ipswich": "Ipswich Town"
}

equipos_a_buscar = [traductor_bd.get(eq, eq) for eq in equipos_usuario]

# Asignamos el rendimiento histórico estadístico para equipos ascendidos sin datos
baseline_pts, baseline_gf, baseline_ga = 38, 38, 63

resultados_finales = []
for equipo in equipos_a_buscar:
    datos_equipo = prediccion[prediccion['Squad'] == equipo]
    if not datos_equipo.empty:
        resultados_finales.append(datos_equipo.iloc[0].to_dict())
    else:
        resultados_finales.append({
            'Squad': equipo, 'Expected_Pts': baseline_pts,
            'Expected_GF': baseline_gf, 'Expected_GA': baseline_ga
        })

tabla_final = pd.DataFrame(resultados_finales).sort_values(by='Expected_Pts', ascending=False)

# ==========================================
# BLOQUE 4: PREPARACIÓN PARA POWER BI Y EXPORTACIÓN
# ==========================================
tabla_final = tabla_final.reset_index(drop=True)
tabla_final.index = tabla_final.index + 1
tabla_final = tabla_final.reset_index().rename(columns={'index': 'Posicion'})

def definir_zona(posicion):
    if posicion == 1: return "Campeón"
    elif posicion <= 4: return "Champions League"
    elif posicion <= 6: return "Europa League"
    elif posicion >= 18: return "Descenso"
    else: return "Media Tabla"

tabla_final['Zona'] = tabla_final['Posicion'].apply(definir_zona)

# 1. Diccionario de URLs de escudos (Extraídos de Wikimedia, formato SVG transparente)
urls_escudos = {
    "Arsenal": "https://upload.wikimedia.org/wikipedia/en/5/53/Arsenal_FC.svg",
       "Bournemouth": "https://upload.wikimedia.org/wikipedia/en/e/e5/AFC_Bournemouth_%282013%29.svg",
    "Brentford": "https://upload.wikimedia.org/wikipedia/en/2/2a/Brentford_FC_crest.svg",
    "Chelsea": "https://upload.wikimedia.org/wikipedia/en/c/cc/Chelsea_FC.svg",
    "Crystal Palace": "https://upload.wikimedia.org/wikipedia/en/a/a2/Crystal_Palace_FC_logo_%282022%29.svg",
    "Fulham": "https://upload.wikimedia.org/wikipedia/en/e/eb/Fulham_FC_%28shield%29.svg",
    "Hull City": "https://upload.wikimedia.org/wikipedia/en/5/54/Hull_City_A.F.C._logo.svg",
    "Ipswich Town": "https://upload.wikimedia.org/wikipedia/en/4/43/Ipswich_Town.svg",
    "Leeds": "https://upload.wikimedia.org/wikipedia/en/5/54/Leeds_United_F.C._logo.svg",
    "Liverpool": "https://upload.wikimedia.org/wikipedia/en/0/0c/Liverpool_FC.svg",
    "Manchester City": "https://upload.wikimedia.org/wikipedia/en/e/eb/Manchester_City_FC_badge.svg",
    "Manchester Utd": "https://upload.wikimedia.org/wikipedia/en/7/7a/Manchester_United_FC_crest.svg",
    "Newcastle": "https://upload.wikimedia.org/wikipedia/en/5/56/Newcastle_United_Logo.svg",
    "Nottingham ": "https://upload.wikimedia.org/wikipedia/en/e/e5/Nottingham_Forest_F.C._logo.svg",
    "Sunderland ": "https://upload.wikimedia.org/wikipedia/en/7/77/Logo_Sunderland.svg",
    "Tottenham": "https://upload.wikimedia.org/wikipedia/en/b/b4/Tottenham_Hotspur.svg",
    "Aston Villa": "https://upload.wikimedia.org/wikipedia/en/thumb/f/f9/Aston_Villa_FC_crest_%282024%29.svg/200px-Aston_Villa_FC_crest_%282024%29.svg.png",
    "Brighton": "https://upload.wikimedia.org/wikipedia/en/thumb/f/fd/Brighton_%26_Hove_Albion_logo.svg/200px-Brighton_%26_Hove_Albion_logo.svg.png",
    "Everton": "https://upload.wikimedia.org/wikipedia/en/thumb/7/73/Everton_FC_logo.svg/200px-Everton_FC_logo.svg.png",
    "Coventry City": "https://en.wikipedia.org/wiki/Coventry_City_F.C.",
}

# 2. Creamos la nueva columna mapeando el diccionario
tabla_final['Escudo_URL'] = tabla_final['Squad'].map(urls_escudos)

# Devolvemos los nombres a como tú los escribiste originalmente para tu dashboard
traductor_inverso = {v: k for k, v in traductor_bd.items()}
tabla_final['Squad'] = tabla_final['Squad'].replace(traductor_inverso)

# Guardamos el archivo
tabla_final.to_excel("/content/Dataset_prediccion_Premier_League.xlsx", index=False)
print("¡Script ejecutado perfectamente! Archivo Dataset_PowerBI_PL_Ascendidos.xlsx generado.")

"""## SImulacion de Montecarlo para predecir las probabilidades de cada equipo de ser CAMPEON"""

import pandas as pd
import numpy as np

# ==========================================
# 1. RECUPERAR LOS DATOS BASE (Igual que el script anterior)
# ==========================================
file_path = "/content/Premier League.xlsx"
xls = pd.ExcelFile(file_path)
all_seasons = []

for i, sheet in enumerate(xls.sheet_names):
    df = pd.read_excel(file_path, sheet_name=sheet)
    if 'Squad' not in df.columns:
        col_name = df.columns[0]
        df_clean = df[col_name].astype(str).str.split(',', expand=True)
        df_clean.columns = [c.strip() for c in col_name.split(',')]
    else:
        df_clean = df.copy()
        df_clean.columns = [str(c).strip() for c in df_clean.columns]

    df_clean = df_clean[['Squad', 'Pts']].copy()
    df_clean['Pts'] = pd.to_numeric(df_clean['Pts'], errors='coerce')
    df_clean['Weight'] = 10 - i
    all_seasons.append(df_clean)

df_all = pd.concat(all_seasons, ignore_index=True)

# Calculamos los puntos base ponderados
def promedio_ponderado(grupo, columna):
    return (grupo[columna] * grupo['Weight']).sum() / grupo['Weight'].sum()

prediccion = df_all.groupby('Squad').apply(
    lambda x: pd.Series({'Expected_Pts': round(promedio_ponderado(x, 'Pts'))})
).reset_index()

# Filtramos tus 20 equipos
equipos_usuario = [
    "Bournemouth", "Arsenal", "Aston Villa", "Brentfors", "Brighton",
    "Chelsea", "Coventry City", "Crystal Palace", "Everton", "Fulham",
    "Hull City", "Ipswich", "Leeds", "Liverpool", "Manchester City",
    "Manchester United", "Newcastle", "Nottingham Forest", "Sunderland AFC", "Tottenham"
]

traductor_bd = {
    "Brentfors": "Brentford", "Manchester United": "Manchester Utd",
    "Nottingham Forest": "Nottingham", "Sunderland AFC": "Sunderland",
    "Leeds": "Leeds United", "Ipswich": "Ipswich Town"
}

equipos_a_buscar = [traductor_bd.get(eq, eq) for eq in equipos_usuario]
baseline_pts = 38
resultados = []

for equipo in equipos_a_buscar:
    datos_equipo = prediccion[prediccion['Squad'] == equipo]
    if not datos_equipo.empty:
        resultados.append(datos_equipo.iloc[0].to_dict())
    else:
        resultados.append({'Squad': equipo, 'Expected_Pts': baseline_pts})

df_base = pd.DataFrame(resultados)


# ==========================================
# 2. MOTOR DE SIMULACIONES MONTE CARLO
# ==========================================
print("Iniciando 10,000 simulaciones de la temporada...")

n_simulaciones = 10000
equipos = df_base['Squad'].tolist()
puntos_base = df_base['Expected_Pts'].values

# Contadores en cero
veces_campeon = {eq: 0 for eq in equipos}
veces_descendido = {eq: 0 for eq in equipos}

# Desviación estándar (históricamente, los equipos de la PL pueden variar +/- 10 puntos por temporada debido a suerte/lesiones)
desviacion = 10

# Generamos matrices de ruido aleatorio para las 10,000 temporadas de un solo golpe (para que sea ultra rápido)
simulaciones_pts = np.random.normal(loc=puntos_base, scale=desviacion, size=(n_simulaciones, len(equipos)))

for i in range(n_simulaciones):
    # Puntos de esta temporada simulada
    puntos_temporada = simulaciones_pts[i]

    # Ordenamos a los equipos según sus puntos (de mayor a menor)
    indices_ordenados = np.argsort(puntos_temporada)[::-1]

    # El primero es el campeón
    idx_campeon = indices_ordenados[0]
    veces_campeon[equipos[idx_campeon]] += 1

    # Los últimos 3 descienden (posiciones 18, 19, 20)
    veces_descendido[equipos[indices_ordenados[-1]]] += 1
    veces_descendido[equipos[indices_ordenados[-2]]] += 1
    veces_descendido[equipos[indices_ordenados[-3]]] += 1

# ==========================================
# 3. EMPAQUETADO FINAL PARA POWER BI
# ==========================================
df_probabilidades = pd.DataFrame({
    'Squad': equipos,
    'Prob_Campeon (%)': [round((veces_campeon[eq] / n_simulaciones) * 100, 2) for eq in equipos],
    'Prob_Descenso (%)': [round((veces_descendido[eq] / n_simulaciones) * 100, 2) for eq in equipos]
})

# Ordenamos por quién tiene más chances de ser campeón
df_probabilidades = df_probabilidades.sort_values(by='Prob_Campeon (%)', ascending=False).reset_index(drop=True)

# Restauramos los nombres originales del usuario
traductor_inverso = {v: k for k, v in traductor_bd.items()}
df_probabilidades['Squad'] = df_probabilidades['Squad'].replace(traductor_inverso)

# Exportamos
df_probabilidades.to_excel("/content/Simulacion_Probabilidades_PL.xlsx", index=False)
print("¡Listo! Archivo 'Simulacion_Probabilidades_PL.xlsx' generado con éxito.")